### ISSUE TITLE
Unable to get plex - times viewed rule to work

### ISSUE THREAD

**Issue by richardquick** [Maintainerr/Maintainerr#1010]
I have the following rule configured and i'm unable to get it to work.  Looking for assistance on finding items that have never been watched.

1st value - Plex - Times Viewed
Action - Smaller
2nd Value - Number
Custom Value - 1

This is returning items that have been watched as identified in Plex.
I have also tried:

1st value - Plex - Times Viewed
Action - Equals
2nd Value - Number
Custom Value - 0

1st value - Plex - Times Viewed
Action - Contains
2nd Value - Number
Custom Value - 0

Can you please assist with where i am going wrong.  I have verified in Plex that the Movies have indeed been watched so they would have a times viewed greater than 0.

thank you.

**Comment by jorenn92** [comment]
Maintainerr will pull the views from Plex’s view history. You can verify in Plex Web if your items have view history records, but they probably don’t.

A recent Plex change impacts this feature. You can read more about it here: https://forums.plex.tv/t/view-history-change-in-1-40-0-x-server-version/863316

Because of this change, this approach isn‘t as reliable as it used to be anymore.

A Tautulli integration will become available in a future version, hopefully that’ll bring a better way to determine the watch state of a media item.

**Comment by richardquick** [comment]
Thank you for the fast response.  Looking forward to the Tautulli integration.  Is there a rough ETA?

**Comment by mlamoure** [comment]
@jorenn92  Now that you have mentioned it, I'm very much looking forward to the Tautulli integration.  Is that expected any time soon?

**Comment by jorenn92** [comment]
> @jorenn92 Now that you have mentioned it, I'm very much looking forward to the Tautulli integration. Is that expected any time soon?

I'm dedicating most of my time to a home renovation project lately, which has left me with limited availability for Maintainerr development. However, once I have more time, the Tautulli integration is one of the first tasks I plan to tackle. I can't say a time frame though.

**Comment by gold007eye** [comment]
@jorenn92 any updates on the tautulli integration for view history?  I just moved some things around between libraries to clean things up, and plex wiped out all the history whereas tautulli still has the accurate view history so now the counter on my rules pretty much starts over.

Here is an example:
After moving this, plex acts like it's never been watched before (even though I did the plex move dance).
![image](https://github.com/user-attachments/assets/91321fe4-81e9-4759-b437-3ab1f22785a2)

**Comment by jorenn92** [comment]
> @jorenn92 any updates on the tautulli integration for view history? I just moved some things around between libraries to clean things up, and plex wiped out all the history whereas tautulli still has the accurate view history so now the counter on my rules pretty much starts over.
> 
> Here is an example: After moving this, plex acts like it's never been watched before (even though I did the plex move dance). ![image](https://private-user-images.githubusercontent.com/4365462/370752686-91321fe4-81e9-4759-b437-3ab1f22785a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyODMxNDYsIm5iZiI6MTcyNzI4Mjg0NiwicGF0aCI6Ii80MzY1NDYyLzM3MDc1MjY4Ni05MTMyMWZlNC04MWU5LTQ3NTktYjQzNy0zYWIxZjIyNzg1YTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjVUMTY0NzI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTZlZWJlZTdhNjYyNWY0OTE5NjdmN2ZlNDE1YzRkZGVmZTRkMDY3YWVkNjU4MGY5YTViNGE2OTU0MDMwYTZmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.IYcas268W56T34uNGy617mQHKfmVptLHJBplQpZ52Sg)

Yes, there’s an active PR currently in draft status https://github.com/jorenn92/Maintainerr/pull/1280

**Comment by gold007eye** [comment]
> Yes, there’s an active PR currently in draft status #1280

If you need a tester for this integration, I would be glad to test :)

**Comment by jorenn92** [comment]
> > Yes, there’s an active PR currently in draft status #1280
> 
> If you need a tester for this integration, I would be glad to test :)

Once it reaches the dev image you're very welcome to report any issue you find!

**Comment by ydkmlt84** [comment]
This is currently available in the dev branch. Reports so far are looking good. Re-open if anything else is needed.
