### ISSUE TITLE
Handling collections failure causing collection handling to stall

### ISSUE THREAD

**Issue by HoustonDad** [Maintainerr/Maintainerr#1046]
**Describe the bug**
Collection handler erroring out 

**To Reproduce**
1. Create a TV Show rule, use the following export: 
```
mediaType: SHOWS
rules:
  - "0":
      - firstValue: Plex.sw_amountOfViews
        action: EQUALS
        customValue:
          type: number
          value: 0
```
Library: TV Shows
Media Type: Shows
Sonarr Action: Unmonitor and delete all seasons / episodes
Take action after days: 2
Keep logs for months: 6
3. Click Save
4. Run Rules
5. Wait a day or two for the "Take action after days" 
6. Collections -> Handle Collections
7. Watch logs

**Expected behavior**
The collection handler will run through the collection, until it errors out with the following, and does not restart / keep going, it seems to crash fully. I have to restart the docker container and click "Handle Collections" to restart it.

```
[maintainerr] | 18/04/2024 17:37:27  [DEBUG] [undefined] GET request failed: AxiosError: Request failed with status code 404
[maintainerr] | 18/04/2024 17:37:27  [ERROR] [ExceptionsHandler] Cannot read properties of undefined (reading 'ratingKey'
```

**Screenshots**
You can see in the screenshot below, the handling failed, did not continue, and I had to restart the container. 
![2Z5aEz499S](https://github.com/jorenn92/Maintainerr/assets/620445/e6787270-723c-4789-969a-a49c868c2760)

**Device (please complete the following information):**
 - OS: Ubuntu 18.04.6 LTS
 - Version:
 ```
ghcr.io/jorenn92/maintainerr    latest        4f5e7f571052   3 weeks ago     660MB
```

**Additional context**
The only workaround I've had is to restart the container.

**Comment by astrodad** [comment]
This is happening to me as well, but I get the same ratingKey error as soon as I click on "Handle Collections".

```
[Nest] 296  - 04/23/2024, 5:00:12 PM     LOG [CollectionWorkerService] Start handling all collections.
[Nest] 296  - 04/23/2024, 5:00:12 PM     LOG [CollectionWorkerService] Handling collection 'TV Shows Leaving Server Soon'
[Nest] 296  - 04/23/2024, 5:00:12 PM     LOG [CollectionsService] Removing media with id 3456 from collection..
[Nest] 296  - 04/23/2024, 5:00:12 PM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'ratingKey')
TypeError: Cannot read properties of undefined (reading 'ratingKey')
    at CollectionWorkerService.handleMedia (/opt/server/dist/modules/collections/collection-worker.service.js:183:99)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CollectionWorkerService.handle (/opt/server/dist/modules/collections/collection-worker.service.js:91:25)
    at async /opt/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at async /opt/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

**Comment by jorenn92** [comment]
Is this issue consistent? Do you have any insight into which media item triggered this error?

It’s desired that Maintainerr handles the error correctly, preventing a crash. However, the presence of a media item lacking a ratingKey suggests potential corruption on Plex’s end.

**Comment by astrodad** [comment]
I was getting this consistently until I upgraded to the latest version yesterday. Nothing changed in terms of the collection, media, or rules. I just re-deployed the container and it worked fine. Sorry, that was not helpful, but I had submitted a comment on this issue before and then deleted it after I realized I was not on the latest.

**Comment by jorenn92** [comment]
Sorry for the late reply. I don't seem to have enough free time to keep up lately..

I added a potential fix in https://github.com/jorenn92/Maintainerr/pull/1069

Once this PR is merged, you'd be able to validate it with the jorenn92/maintainerr:develop or ghcr.io/maintainerr:main images.

**Comment by dperez-sct** [comment]
I have this rule:

```mediaType: SHOWS
rules:
  - "0":
      - firstValue: Tautulli.addDate
        action: BEFORE
        customValue:
          type: custom_days
          value: "400"
      - operator: AND
        firstValue: Sonarr.monitored
        action: NOT_EQUALS
        customValue:
          type: boolean
          value: "true"
      - operator: AND
        firstValue: Tautulli.sw_amountOfViews
        action: EQUALS
        customValue:
          type: number
          value: 0
```

When press Handle collections give me this on logs:

```[maintainerr] | 06/01/2025 00:42:58  [INFO] [CollectionWorkerService] Start handling all collections
[maintainerr] | 06/01/2025 00:42:58  [INFO] [CollectionWorkerService] Handling collection 'no visto y no pedido seriess'
[maintainerr] | 06/01/2025 00:42:58  [INFO] [CollectionsService] Removing media with id 1570 from collection..
TypeError: Cannot read properties of undefined (reading 'ratingKey')
    at CollectionWorkerService.handleMedia (/opt/app/server/modules/collections/collection-worker.service.js:276:67)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CollectionWorkerService.execute (/opt/app/server/modules/collections/collection-worker.service.js:79:25)```
