### ISSUE TITLE
Interesting Feature request (like NETFLIX)

### ISSUE THREAD

**Issue by gianfelicevincenzo** [Maintainerr/Maintainerr#1093]
I would like to propose an interesting request, also for users as it is much more understandable.  Implement functionality like Netflix that notifies you when the movie will be removed from the site.  It would be interesting to see something like this here on plex too, modifying the poster image currently in use in a film with a "red band" (like Netflix) in which the date of when it will be eliminated is written.  I hope you will consider this request

**Comment by mlamoure** [comment]
That is mostly what the Collections in Maintainerr do.  They can be added to all user home pages so that they see them.  I call mine "Movies Leaving Plex Soon" and "TV Seasons Leaving Plex Soon".

Changing the poster seems a bit of a stretch for this app, but the author can comment on that.  Another option is to look at Kometa.

**Comment by vincenzogianfelice** [comment]
in my opinion no, also because it is more easily visible for users (also because as you well know the plex homepage is a bit of a mess). Maybe this option could be "an extra" that can always be useful. I've never heard of Kometa, but I would have liked to have it here

**Comment by vincenzogianfelice** [comment]
@Droppisalt nice, what I was looking for.  I ask you a question: is it possible via kometa to set a deletion "timer" for films?  I ask quickly, since unfortunately I don't have time to look at both software well.  If so, switch kometa as soon as I have time

**Comment by jorenn92** [comment]
I agree that this is a bit out of scope for this project. As mentioned before, you can achieve the behavior you want by using Maintainer in conjunction with Kometa.
