### ISSUE TITLE
Can't login to APIs

### ISSUE THREAD

**Issue by brando56894** [Maintainerr/Maintainerr#1118]
Edit: this isn't specific to Plex apparently, Radarr and Sonarr shows this issue as well.

Regardless of what URLs are used I get the following reports in the container log when I attempt to login to the Plex server's API. I am able to authenticate with Plex Inc's servers so that it will grab the list of servers associated with my account.

```
[maintainerr] | 01/06/2024 15:49:31  [WARN] [PlexApiService] Plex api communication failure.. Is the application running?
[maintainerr] | 01/06/2024 15:49:31  [DEBUG] [PlexApiService] Cannot read properties of undefined (reading 'queryWithCache')
[maintainerr] | 01/06/2024 15:49:31  [DEBUG] [SettingsService] Cannot read properties of undefined (reading 'version')
```

It lists 8 addresses, both secure and insecure, but only two of them are the IPs of my server (the others are in private address spaces, which is interesting considering I'm using host mode).

**To Reproduce**
* Start with a fresh container, Maintainerr is using bridge mode with the necessary ports exposed and Plex is using host mode. 
* Click _authenticate_ and sign in via the Plex SSO, click _refresh_, select a server, hit _Test Server_
* The following error shows up in the UI: **Connection failed! Please check and save your settings** which shows the above errors

**Expected behavior**
I'm able to authenticate the the Plex Server's API

**Screenshots**
List of servers, mine is **192.168.1.7**, not sure why it shows the others, they don't show under **Authorized Servers** in Plex.
![image](https://github.com/jorenn92/Maintainerr/assets/572116/1f0c020f-36f6-4f13-ac3e-69bf912e4011)

After clicking _**Test Server**_ It doesn't matter if I use the server from the dropdown or enter it manually , the same error shows
![image](https://github.com/jorenn92/Maintainerr/assets/572116/88d47829-0191-440f-abc7-85c58d5e9991)

**Device (please complete the following information):**
 - OS: Arch Linux with Docker
 - Version: (Docker server) 26.1.0

**Other Info**
Other apps have no issues logging into and using Plex's API

**Comment by ydkmlt84** [comment]
This may not be your problem but the Test Saved button doesn't work unless you click on save changes first. Then Test Saved.

**Comment by brando56894** [comment]
Yeah I think that was it, I said "screw it" and hit _save_ anyway and then went to the homepage and noticed it showed everything for Plex. There should probably be a warning for this IMO.

**Comment by ydkmlt84** [comment]
A warning that states, "clicking test saved, tests the saved config and not whatever you had in there before you saved it"?

**Comment by jorenn92** [comment]
I named it 'Test Saved' to indicate that it tests the saved configuration. While I'm aware this isn't ideal, it should test the current input, it was the quickest way to implement a basic testing feature at the time.
