### ISSUE TITLE
Change sort title on collections created by maintainerr

### ISSUE THREAD

**Issue by nmbrg** [Maintainerr/Maintainerr#1149]
At the moment when maintainerr creates a collection, that collection gets the same sort title in plex as the title of the collection (that gets the name from the rule in maintainerr). and there seem to be no way to edit that.

**To Reproduce**
1. create rule in maintainerr, name it "whatever"
2. collection gets created in maintainerr with the name "whatever"
3. collection gets created in plex with the name "whatever"
4. the collection in plex now has sort title set to "whatever"
5. manually edit sort title in plex to "something else".
6.  maintainerr removes/rebuilds collection when nothing is about to be deleted (or if its at every run, not sure when it happens)
7. collection gets added to plex again, now with sort title set to "whatever" again.

**Expected behavior**
1. create rule in maintainerr, name it "whatever"
2. configure a sort title for the collection that will be created (either in the rules or the collection in maintainerr) and set that to "something else"
3. collection gets created with the name "whatever" and a sort title set to "something else".
4. collection gets removed and/or rebuilt in plex by maintainerr.
5. collection gets added by maintainerr again still with the sort title set to "something else".

**Screenshots**
How it is at the moment in plex:
![Namnlös](https://github.com/jorenn92/Maintainerr/assets/31845361/e56f9711-580b-4ccf-abbb-9e642b151666)

How i want it to be:
![Namnlös2](https://github.com/jorenn92/Maintainerr/assets/31845361/a9b1ce96-97d1-4524-8e9d-0597d75ee55e)

**Device (please complete the following information):**
 - OS: Docker
 - Version 2.0.4 (Maintainerr)

**Additional context**
In my case i want the collections to be able to have the same sorting as Kometa default collections, but at the moment that seems impossible since i cant add the !010_ before the title of the collection, in the sort title, without getting it removed ever so often automatically by maintainerr.

**Comment by jorenn92** [comment]
I'll transform this into a FR. This won't be hard to add as a configuration option during rule creation.
