### ISSUE TITLE
Cannot sync with Plex

### ISSUE THREAD

**Issue by Dal78** [Maintainerr/Maintainerr#1196]
**Describe the bug**
On a fresh install, with correct permissions set on file structure, following docker compose guide on Synology NAS plex cannot retreive a list of plex servers although confirms list retrieved successfully.

Plex account connects fine with authenticate button.

Manual entry of secure or insecure plex hostnames or local IP adresses yields a failed test and no integration to plex.

Other apps such as overseer are fine running on the same docker network.

Can someone else check a clean setup to identify if this is something unique to my configuration / plex user?

**Device (please complete the following information):**
 - OS: DS 923+
 - Version: DSM 7.2.1-69057 Update 5

**Comment by jorenn92** [comment]
Hey! Did you  authenticate first before attempting to fetch available servers?

**Comment by Dal78** [comment]
Confirmed.  Tried it just now again on a clean container.


________________________________

**Comment by jorenn92** [comment]
Are there any errors in the logs? I’ll try myself when i’ve got some time on my hands, but it sounds like the network calls fail for some reason.

**Comment by Dal78** [comment]
How strange, i enabled debug to get more verbosity and it  refreshed the list of servers out of the box this morning and works.

Still works with debug off.  Maybe something funny going on with plex infrastructure ?

**Comment by jorenn92** [comment]
It's possible Plex had some issues on your initial attempt, we fetch the account's servers from a public Plex URL.
I also wasn't able to reproduce it when I tried earlier this week.

I'll close this issue for now. If you do happen to notice it again, you're free to open a new issue and link to this one.
