### ISSUE TITLE
Axios error when running TV Shows rule only

### ISSUE THREAD

**Issue by markwoodward86** [Maintainerr/Maintainerr#1201]
**Describe the bug**
I seem to get a lot of lines for an Axios error when running the rule i have set up for TV Shows. The Movies rule runs without issue so i know the Plex authentication is working.

**To Reproduce**
I only have a simple rule that is mirrored from Movies and it is if label 'temporary' exists in Sonarr and the show was added to Plex before 60 days then add to 'Leaving Soon' collection. 

Leaving Soon collections exist in both my Movies library and my TV Shows library and even have a manually added show inside for good measure.

Again, Movies rule executed without issue.

**Expected behavior**
Rule executes

**Screenshots**
Debug logs below

**Device (please complete the following information):**
 Latest image of Maintainerr managed using watchtower in a up to date Debian LXC on Proxmox, latest image of Plex in a virtual machine. 

**Additional context**

```
[maintainerr] | 06/08/2024 22:01:32  [DEBUG] [undefined] GET request failed: AxiosError: Request failed with status code 404
[maintainerr] | 06/08/2024 22:01:32  [DEBUG] [undefined] GET request failed: AxiosError: Request failed with status code 404
[maintainerr] | 06/08/2024 22:01:32  [DEBUG] [undefined] GET request failed: AxiosError: Request failed with status code 404
[maintainerr] | 06/08/2024 22:01:55  [INFO] [RuleExecutorService] Adding 95 media items to 'Leaving Soon'.
[maintainerr] | 06/08/2024 22:01:55  [INFO] [CollectionsService] Adding media with id 38980 to collection..
[maintainerr] | 06/08/2024 22:01:55  [DEBUG] [PlexApiService] Plex Server didnt respond with a valid 2xx status code, response code: 400
[maintainerr] | 06/08/2024 22:01:55  [WARN] [Error: Plex Server didnt respond with a valid 2xx status code, response code: 400] Couldn't add media to collection: 
```

**Comment by markwoodward86** [comment]
It appears to only be present when targeting TV Shows - episodes. When i change this to season or show i only get the plex API error and not the axios error. Trouble is i only want to use this rule to delete specific episodes and not entire seasons or shows.

**Comment by jorenn92** [comment]
If you want, you can try out the 'ghcr.io/jorenn92/maintainerr:main' image, this one should contain better logging on network errors.  Hopefully, an explanation for the failing calls can be concluded this way.

Please note that I don't advise to stay on this image for long, since it'll be built after each git push. So the image could become unstable at any time.

**Comment by markwoodward86** [comment]
> If you want, you can try out the 'ghcr.io/jorenn92/maintainerr:main' image, this one should contain better logging on network errors. Hopefully, an explanation for the failing calls can be concluded this way.
> 
> Please note that I don't advise to stay on this image for long, since it'll be built after each git push. So the image could become unstable at any time.

thanks for the tip. The axios error has disappeared but the 400 error persists. I wonder if this is because individual episodes cannot be added to a collection? I dont seem to be able to do that manually so maybe that is the issue. My use case is to delete episodes that were requested by other people once they have watched them. Unfortunately i dont want to delete and unmonitor the whole season as they will still want the next episode.
