### ISSUE TITLE
Watchlisted rule is missing.

### ISSUE THREAD

**Issue by TinyBabyOwl** [Maintainerr/Maintainerr#1202]
**Describe the bug**
In the rules glossary in the documentation there is a rule called "Watchlisted by (username)", but that rule does not show up in the app.

**To Reproduce**
1. Go to a rule
2. Select first value
3. No "Watchlisted by (username)" or anything about watchlists in the options

**Expected behavior**
Available rules should match documentation

**Device (please complete the following information):**
 - OS: Ubuntu
 - Version 2.0.4

**Comment by jorenn92** [comment]
That rule is currently only available in the next develop image, it’s unreleased yet. Since the documentation doesn’t work with branches, the rule is already mentioned there.
