### ISSUE TITLE
Cant connect to Plex Radarr or Sonarr

### ISSUE THREAD

**Issue by Vagenthar** [Maintainerr/Maintainerr#1229]
Did not change any settings the application worked fine and suddenly this happened.

2024/08/22 11:51:33 | stdout | [maintainerr] \| 22/08/2024 11:51:33  [WARN] [PlexApiService] Plex api communication failure.. Is the application running?
-- | -- | --
2024/08/22 11:51:28 | stdout | [maintainerr] \| 22/08/2024 11:51:28  [WARN] [PlexApiService] Plex api communication failure.. Is the application running?
2024/08/22 11:50:28 | stdout | [maintainerr] \| 22/08/2024 11:50:28  [INFO] [CollectionWorkerService] Not all applications are reachable.. Skipping collection handling
2024/08/22 11:50:28 | stdout | [maintainerr] \| 22/08/2024 11:50:28  [INFO] [CollectionWorkerService] Start handling all collections
2024/08/22 11:50:28 | stdout | [maintainerr] \| 22/08/2024 11:50:28  [WARN] [SonarrApi] Couldn't fetch Sonarr info.. Is Sonarr up?
2024/08/22 11:50:18 | stdout | [maintainerr] \| 22/08/2024 11:50:18  [WARN] [RadarrApi] Couldn't fetch Radarr info.. Is Radarr up?
2024/08/22 11:50:08 | stdout | [maintainerr] \| 22/08/2024 11:50:08  [WARN] [PlexApiService] Plex api communication failure.. Is the application running?
2024/08/22 11:50:01 | stdout | [maintainerr] \| 22/08/2024 11:50:01  [INFO] [RuleExecutorService] Starting Execution of all active rules
2024/08/22 11:49:55 | stdout | }
2024/08/22 11:49:55 | stdout | code: 'ECONNRESET'
2024/08/22 11:49:55 | stdout | at TCP.<anonymous> (node:net:338:12) {
2024/08/22 11:49:55 | stdout | at Socket.emit (node:events:531:35)
2024/08/22 11:49:55 | stdout | at Socket.socketCloseListener (node:_http_client:473:25)
2024/08/22 11:49:55 | stdout | Error: socket hang up
2024/08/22 11:49:55 | stdout | }
2024/08/22 11:49:55 | stdout | code: 'ECONNRESET'
2024/08/22 11:49:55 | stdout | at TCP.<anonymous> (node:net:338:12) {
2024/08/22 11:49:55 | stdout | at Socket.emit (node:events:531:35)
2024/08/22 11:49:55 | stdout | at Socket.socketCloseListener (node:_http_client:473:25)
2024/08/22 11:49:55 | stdout | Failed to proxy http://localhost:3001/api/plex/libraries Error: socket hang up
2024/08/22 11:49:50 | stdout | }
2024/08/22 11:49:50 | stdout | code: 'ECONNRESET'
2024/08/22 11:49:50 | stdout | at TCP.<anonymous> (node:net:338:12) {
2024/08/22 11:49:50 | stdout | at Socket.emit (node:events:531:35)
2024/08/22 11:49:50 | stdout | at Socket.socketCloseListener (node:_http_client:473:25)
2024/08/22 11:49:50 | stdout | Error: socket hang up
2024/08/22 11:49:50 | stdout | }
2024/08/22 11:49:50 | stdout | code: 'ECONNRESET'
2024/08/22 11:49:50 | stdout | at TCP.<anonymous> (node:net:338:12) {
2024/08/22 11:49:50 | stdout | at Socket.emit (node:events:531:35)
2024/08/22 11:49:50 | stdout | at Socket.socketCloseListener (node:_http_client:473:25)
2024/08/22 11:49:50 | stdout | Failed to proxy http://localhost:3001/api/plex/libraries Error: socket hang up

**Comment by jorenn92** [comment]
Does this persist after a reboot?

**Comment by Vagenthar** [comment]
Yes.

**Comment by jorenn92** [comment]
I don't really know what's going on here. You could try to use the latest main/develop docker image and enable debug logging to hopefully get some more info. On first glance, this seems like a network issue.

**Comment by ydkmlt84** [comment]
@Vagenthar did you ever get a resolution?

**Comment by Vagenthar** [comment]
It was a network issue related to Tailscale running on synology. You can find a solution to https://tailscale.com/kb/1131/synology. See enable outbound connections if you have the same setup.

**Comment by ydkmlt84** [comment]
Thanks for the reply! Glad you got it figured out.
