### ISSUE TITLE
Plex - [list] Users that watch the show/season/episode data not being saved

### ISSUE THREAD

**Issue by Subduing5805** [Maintainerr/Maintainerr#1341]
I have a rule that compares user that have watched all available episodes with users that watch the show and the 'Plex - [list] Users that watch the show/season/episode' rule keeps flip-flopping between the user and 'null' resulting in the season being periodically added and removed from the collection.

The yaml:
`        
  - operator: AND
    action: equals
    firstValueName: Plex - [list] Users that saw all available episodes
    firstValue:
      - xxxx
    secondValueName: Plex - [list] Users that watch the show/season/episode
    secondValue:
      - xxxx
    result: true
`

![image](https://github.com/user-attachments/assets/ac077cd0-a96a-472d-bf98-967940efd696)

Docker ver 2.1.2 on Synology

**Comment by ben-propflo** [comment]
Is there anything suspect in your application logs around those times? If not, could you try setting `DEBUG=true`. Wait for the problem to occur again and share your log.

**Comment by benscobie** [comment]
Is there anything suspect in your application logs around those times? If not, could you try setting DEBUG=true. Wait for the problem to occur again and share your log.

**Comment by Subduing5805** [comment]
I must apologise, seems like the issue may not be specific to that rule. It's just that that rule errored out last time i was able to get a 'false' test on the media. Just tested again this morning and this is the result:

![image](https://github.com/user-attachments/assets/9203ca33-5d6a-4cea-8c54-eafa4024f3e1)

Attached test result, rule & log.

[rule.txt](https://github.com/user-attachments/files/17593714/rule.txt)
[test.txt](https://github.com/user-attachments/files/17593715/test.txt)
[log.txt](https://github.com/user-attachments/files/17593706/log.txt)

**Comment by Subduing5805** [comment]
Sorry new to github, didn't mean to close.

**Comment by Subduing5805** [comment]
Sorry new to github didn't mean to close.

**Comment by ydkmlt84** [comment]
> I must apologise, seems like the issue may not be specific to that rule. It's just that that rule errored out last time i was able to get a 'false' test on the media. Just tested again this morning and this is the result:
> 
> ![image](https://private-user-images.githubusercontent.com/111436898/382123996-9203ca33-5d6a-4cea-8c54-eafa4024f3e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0Njg0MTIsIm5iZiI6MTczMDQ2ODExMiwicGF0aCI6Ii8xMTE0MzY4OTgvMzgyMTIzOTk2LTkyMDNjYTMzLTVkNmEtNGNlYS04YzU0LWVhZmE0MDI0ZjNlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQxMzM1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNzg2YTdiZDFkNGJlODQ5NzM5MmQxNDNkODBjODllZjFmY2FkNzRiYWZiMGY3YjdjNDFlOWQ0MmQ5NWFkNzM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.u1qZhdkEYGpet8y0c52eAUzIlGhaUvfrNy9tyYMKRzs)
> 
> Attached test result, rule & log.
> 
> [rule.txt](https://github.com/user-attachments/files/17593714/rule.txt) [test.txt](https://github.com/user-attachments/files/17593715/test.txt) [log.txt](https://github.com/user-attachments/files/17593706/log.txt)

Correct me if I am wrong, but in the first example you are looking to compare users that saw all available episodes against users that watch the show.
```
operator: AND
action: equals
firstValueName: Plex - [list] Users that saw all available episodes
firstValue:
xxxx
secondValueName: Plex - [list] Users that watch the show/season/episode
secondValue:
xxxx
result: true
`
```
and in the second example this isn't even a part of your test results.

You are saying that sometimes it will be null, instead of the actual user? Also, that it is happening on the same media item? Or are some null and some have the intended results?

It may be best/easier to switch this to a Discord discussion. Want to come over there and we can further discuss? [Discord Invite](https://discord.gg/WP4ZW2QYwk)

**Comment by Subduing5805** [comment]
Hey guy appreciate the help, my issue appears to be resolved. 
Is it possible a rule name with brackets could cause the above behaviour? Otherwise I have no ideas.

**Comment by benscobie** [comment]
That shouldn't cause any issues. I'll close this for now but please feel free to raise another issue and include logs if you come across it again.
