### ISSUE TITLE
Viewed by (username) not present for "TV Shows" Media Type

### ISSUE THREAD

**Issue by MWatter** [Maintainerr/Maintainerr#1342]
**Describe the bug**
The " Viewed by (username)" is missing from the "First Value" dropdown when any "TV Shows" media type is selected. 

**To Reproduce**
1. Go to 'Rules'
2. Click on 'TV Shows' from Library
3. Select "Episodes" ffor media type
4. Scroll down to 'Rules -> Section 1'
5. Click the drop down for "First Rule"
6. Observe that "Viewed by (username) is not in the list

**Expected behavior**
I'm very new to Maintainerr, so it's possible I'm missing something, but I believe "Viewed by (username)" should be in the dropdown.

**Device (please complete the following information):**
 - OS: Official Docker 
 - Version 2.1.2

**Additional context**
I am only using Plex and Sonarr as connected applications. Both are properly connected and pass connection checks.

**Comment by ydkmlt84** [comment]
What you are looking for is called `Users that watch the show/season/episode`, but you are correct it is named `Viewed by` when you are on a Movies library.

![image](https://github.com/user-attachments/assets/9d5f9578-30b9-476c-aa77-071250dc8834)

**Comment by ydkmlt84** [comment]
I am marking this as closed. If you require further assistance, please open a new issue.

**Comment by gshpychka** [comment]
@ydkmlt84 `Viewed by (username)` and `Users that watch the show/season/episode` are two different rules, according to the docs (keys `Plex.seenBy` and `Plex.sw_watchers` respectively).

The [docs](https://docs.maintainerr.info/latest/Glossary/#viewed-by-username) say that the former is available for all media types:

> Availability: movies, shows, seasons, episodes

whereas it is only available for movies.
