### ISSUE TITLE
Support connecting to remote apps over SSL +.+

### ISSUE THREAD

**Issue by 8a8al00ey** [Maintainerr/Maintainerr#377]
**Is your feature request related to a problem? Please describe.**
Should be able to connect to SSL endpoints

**Describe the solution you'd like**
Connect to apps via SSL endpoints

<img width="1004" alt="Screen Shot 2023-02-08 at 5 13 41 PM" src="https://user-images.githubusercontent.com/109389709/217663356-37d3f141-aa51-4649-94b5-376270408b17.png">

```
[Nest] 54  - 02/08/2023, 5:28:15 PM    WARN [PlexApiService] Plex api communication failure.. Is the application running

**Comment by jorenn92** [comment]
Fixed in PR https://github.com/jorenn92/Maintainerr/pull/442.
