### ISSUE TITLE
[Feature request] Add rule for plex watched status

### ISSUE THREAD

**Issue by kiwi3007** [Maintainerr/Maintainerr#466]
**Is your feature request related to a problem? Please describe.**
Rules currently include number of times played, however if media is added, then manually marked as played, it does not have a play count. 

**Describe the solution you'd like**
Add a rule which allows rules based on whether media is marked as watched or not, not just based on number of plays.

**Comment by jorenn92** [comment]
Hi, good catch!

I’ll add the rule in the next release.

**Comment by jorenn92** [comment]
This isn't a quick fix as I first thought it would be... The correct data has to be fetched from an external Plex API (discover.plex.tv), not your own server. 

While this isn't a dealbreaker, it will take longer to implement right.

**Comment by jorenn92** [comment]
I've spent some time trying to figure out this issue. It appears my previous comment was false. Plex's Discover API isn't the answer here. This will only return the play status of the currently logged in account, which is of nu use. 

But during my testing with the current implementation, Plex's watch state response did include items that were manually tagged as watched. 

Are you seeing this on all your media? Or is this an edge case?

**Comment by kiwi3007** [comment]
Creating a rule to capture movies which have greater than 0 plays in plex creates a collection of 94 movies, creating the same filter in plex gives 195. The ones missing don't have a play history within Plex, but they are marked as watched.

**Comment by jorenn92** [comment]
That’s odd. On my Plex instance, it also creates a play history record when i mark an item as watched. I’ll do some more digging..

**Comment by jorenn92** [comment]
I don't know what caused this issue on your server. I always get a play history record when I mark an item as watched. 

I do find it odd that Plex sometimes fetches watch states from the 'discover.provider.plex.tv' userState endpoint. I have a feeling that your watch states are coming from that endpoint, which would mean they got lost on your server somehow (but are saved in your account). Maybe you cleansed data or your server got rebuild at some point in time?

Since I can't use this endpoint within Maintainerr because it needs auth tokens for each user, I don't think this is something I can fix.

**Comment by Animosity022** [comment]
I've toyed around with the PlexAPI tools a bit and that does grab watch status as I use that a bit and was looking for something similar as I wanted to delete only seasons not watched by me for certain shows so I was looking for  a watched flag as well and not plays.

https://www.reddit.com/r/PleX/comments/zk7rhh/comment/izye2yu/?utm_source=share&utm_medium=web2x&context=3

For 'dumb' shows on my server that other friends watch use a label to mark them autowatched as it loops through unwatched episodes. Not great code, but works.

```
#!/usr/bin/python3

# This is just a small utility I use to mark shows watched that I don't actually care about
# I edit the TV shows and make their Sharing tag "AutoWatch" and this script runs in cron
# to mark them watched so they don't clutter up my plex screen

import os
import subprocess
import sys
os.environ['PLEXAPI_CONFIG_PATH'] = "/mnt/user/data/scripts/plexapi.ini"

from plexapi.server import PlexServer
plex = PlexServer()

tv = plex.library.section('TV Shows')
for shows in tv.search(label='AutoWatch'):
    for episode in shows.unwatched():
        episode.markPlayed()

tv = plex.library.section('TV (Other)')
for shows in tv.search(label='AutoWatch'):
    for episode in shows.unwatched():
        episode.markPlayed()
```
