### ISSUE TITLE
[BUG] No movies added to collection based on rule

### ISSUE THREAD

**Issue by ChadTaljaardt** [Maintainerr/Maintainerr#471]
**Describe the bug**
I have a rule that **should** be adding a lot of movies for deletion, but after running the movies, nothing gets added to the collection for deletion. 

**To Reproduce**
1. Create a rule: `Plex: Times Viewed` -> `EQUALS` -> `NUMBER` -> `0`
2. Run Rules.

**Expected behavior**
A collection be created with many movies. 

**Screenshots**

<img width="662" alt="Screenshot 2023-09-15 at 10 52 10 AM" src="https://github.com/jorenn92/Maintainerr/assets/13891249/1ce41ca5-4728-4b28-832c-4d02d0e34316">
<img width="424" alt="Screenshot 2023-09-15 at 10 52 15 AM" src="https://github.com/jorenn92/Maintainerr/assets/13891249/b834eb0e-34d7-4f64-a481-41ec51a982e2">

**Device (please complete the following information):**
 - OS: Unraid
 - Version: `latest`

**Comment by jorenn92** [comment]
Hey, that should work.

Did you wait long enough? If you have a huge library, it might take a while.

Could you add your log (stdout)? 
If there's no  'Execution of rules for '<your name>' done.' line, it's still working.

**Comment by ChadTaljaardt** [comment]
You are correct, I never waited long enough. We can close this issue. 

I think it might be good if we can add a indicator somewhere saying the rule is still processing.
