### ISSUE TITLE
[Feature Request] Add more season/episode fields to the filteroptions

### ISSUE THREAD

**Issue by appiekap653** [Maintainerr/Maintainerr#509]
**Is your feature request related to a problem? Please describe.**
When using the Season or Episode filter-type it will be handy to have some filter fields to make sure Maintainerr doesn't delete the whole season while some episode are still unaired.

When you have for example:
Plex - Users that saw all available episodes contains Mark, and you have set to delete after 5 days.

When there are 3 episodes available for a season of 10 episodes because the rest is still unaired, and you watch those 3 episodes.
Maintainerr will delete the whole after 5 days. If a new episode is released within the 5 days it will not delete, but when the next episode is released within 7 days, it will be deleted by Maintainerr before that date.

**Describe the solution you'd like**
Add some filter fields like:

Sonarr - Total amount of episodes for this season
Plex - Amount of available episodes for this season
Sonarr - Episode-Number of last episode of this season
Plex - Episode-Number of last seen episode

This way you can make sure that when only dealing with whole seasons you can make the rule:
Plex - Amount of available episodes for this season == Sonarr - Total amount of episodes for this season

Or when dealing with partial seasons (example: S01E03 till S01E10 is available on Plex where E10 is the last):
Plex - Episode-Number of last seen episode == Sonarr - Episode-Number of last episode of this season

**Comment by jorenn92** [comment]
Hey, sorry for my very late reply...

I added/clarified a few extra Sonarr rule values that might help with what you're trying to accomplish. 

- Sonarr - Has unaired episodes (Boolean whether a show / season has unaired (monitored) seasons / episodes)
- Sonarr - Season has unaired episodes (On episodes only, boolean whether the parent season has unaired episodes)

You could use these new rules to filter seasons, shows & episodes with unaired episodes out of your collections. I believe this is what you'd like to do?

Unrelated to this issue, but perhaps worth mentioning, these values are also added:
- Sonarr - Number of monitored seasons / episodes (Amount of seasons in the show, or episodes in the season, that are monitored)
- Sonarr - Number of seasons / episodes (also unmonitored) (Same as above, but also counting the unmonitored seasons / episodes)

These changes will be available in the next release. (Sooner on the 'develop' docker tag)
