### ISSUE TITLE
[Bug] "Platform 'Maintainerr' not matched by plugin platform requirements" notice in Plex logs, deletion not happening

### ISSUE THREAD

**Issue by h20534** [Maintainerr/Maintainerr#580]
Hello,

I set up maintainerr via unraid docker, sitting alongside my Plex, Radarr, and Sonarr containers. All run on the same subnet, and are able to talk to each other successfully. When clicking the "Handle Collections" button in Maintainerr, the following notice is posted in the Plex logs:

`Nov 06, 2023 18:54:47.603 [22671960820536] Debug — Request: [192.168.1.6:51892 (Subnet)] GET / (11 live) #10d017 GZIP Signed-in Token ($ADMINUSERNAME) (117.0.0.0)
Nov 06, 2023 18:54:47.604 [22671960820536] Debug — [Req#10d017] (Capabilities) Platform 'Maintainerr' not matched by plugin platform requirements`

And the movies/tv shows are not deleted. Maintainerr is successfully connected to & authenticated against my Plex server.

Plex Server Version: 1.32.7.7621  
Maintainerr Version: Latest Available
Any help would be appreciated, thanks! I can provide more logs if needed.

**Comment by jorenn92** [comment]
Hey, thanks for reporting this! 

I can't seem to reproduce this myself. 

Is this the only thing you notice on Maintainerr's side? Are you seeing the media cards on the Overview screen and is Maintainerr able to create collections after running rules? If yes, the API connection is working.

Collection handling will only delete media when it has lived in the collection for longer than the specified amount of time in the rule settings, so perhaps it's normal that nothing is removed yet? 

Maintainerr doesn't delete from Plex directly. By default, it tells Radarr / Sonarr to remove media. Only when these are not configured will Maintainerr tell Plex to remove media.

If these messages persist, you could try to re-authenticate Maintainerr. From what I find online, this message occurs when a client isn't authenticated.

**Comment by h20534** [comment]
Thanks for the reply!

Yes, Maintainerr is able to pull images and make the collections after setting the rules, so the API connection is working. I have a rule set to delete media 180 days after hitting the Plex server, and I have plenty of media older than 180 days. 

Question - it seems like it is literally waiting 180 days before deleting the media in the collection. My understanding of the “Handle Collections” button was that clicking that will delete any media in the collection immediately instead of waiting. Is that incorrectly?

I will try to reauthenticate and report back.

**Comment by jorenn92** [comment]
No problem! I don't think there's anything wrong with the Plex API connection if it's able to create collections and add media to them (and if you're able to see the collection in Plex).

The 'handle collection' button does exactly the same as the batch process that runs every 12 hours. It will check if there's media in your collection that has been there for longer than the amount of days specified in the rule's 'Media deleted after days' parameter. If yes, it'll remove or unmonitor the media (depending on your other rule config).

How does your rule look? Do you see the expected media being added to the collection?

**Comment by jorenn92** [comment]
Your rule looks good, but by setting 180 as the 'media deleted after days' param, Maintainerr will add media to the collection and wait for 180 days to do the delete actions. If you want it to happen sooner, you'll have to change that parameter, the minimum being 1 (i'm actually not sure what would happen if you specify 0)

**Comment by jorenn92** [comment]
Closed because of inactivity
