### ISSUE TITLE
[Feature Request] Integration with Tautulli

### ISSUE THREAD

**Issue by bulfinch** [Maintainerr/Maintainerr#602]
**Is your feature request related to a problem? Please describe.**
When running a rule on a large library there is a material impact on the performance of Plex. The reason for this is not completely clear as maintainerr is on machine A and Plex is on machine B. Perhaps it's a lot of Plex API calls? Plex is installed on a relatively low power machine,  but when a maintainerr scan is active, it coincides with reports from users that Plex is performing poorly. In the Plex CPU dashboard the usage is often 100% when maintainerr runs.

**Describe the solution you'd like**
I'd like to have the option to pull Plex data from Tautulli so there's as little interaction between Plex and maintainerr as possible to improve Plex performance. 

**Describe alternatives you've considered**
An alternative would be to add cron settings so maintainerr can be run during low usage periods.

**Comment by jorenn92** [comment]
Depending on your rules and library, there’ll be a lot of API calls. It has to do this to fetch the information needed for rule execution.

There’s definitely room for improvement there though.

Until then, it’s actually possible to configure the schedule with cron rules. I implemented this on the backend but never got around to the UI side.
However, you can load the sqlite db file in a sqlite editor and navigate to the settings table. There should be 1 value with 2 cron values for collection & rule handling. You could update these values with the cron schedule you like.

**Comment by jorenn92** [comment]
I finished the UI of the jobs settings screen in https://github.com/jorenn92/Maintainerr/pull/604, it’ll be available in the upcoming release

**Comment by jorenn92** [comment]
Also, significant enhancements were made to the caching mechanism in https://github.com/jorenn92/Maintainerr/commit/478da57a9f6d828e34b9f2a5fcf527a61df09529. With these improvements, the rule execution process will efficiently utilize Plex responses by reusing them when identical data is required.

**Comment by Migz93** [comment]
Would also like an integration with Tautulli, to give another usecase is that I've just had to setup a new plex server and even though i followed the plex guide to migrate watch state it appears that this doesn't copy info to the same place that the Plex API reads from.

Because my rules all contain "Times Viewed" I now have almost everything flagging to be removed.
If we had the option to integrate with Tautulli I could use "Times Viewed" from there instead.

Really appreciate your work on this tool!

**Comment by jorenn92** [comment]
> Would also like an integration with Tautulli, to give another usecase is that I've just had to setup a new plex server and even though i followed the plex guide to migrate watch state it appears that this doesn't copy info to the same place that the Plex API reads from.
> 
> Because my rules all contain "Times Viewed" I now have almost everything flagging to be removed. If we had the option to integrate with Tautulli I could use "Times Viewed" from there instead.
> 
> Really appreciate your work on this tool!

Integration with Tautulli will be added soon. I've come across some compelling use cases in the past few months. While it will not be included in the next release, it shouldn't be too far off either.
