### ISSUE TITLE
Add Playlists to rules conditions

### ISSUE THREAD

**Issue by solid-pixel** [Maintainerr/Maintainerr#608]
Hey,
first of all, thank you so much for this fantastic piece of software, it's AMAZING 👏🏻

I stream Plex content through Infuse on AppleTV, and I was looking for a way to prevent certain movies from being removed by Maintainerr's rules within Infuse itself.

With the Plex app this would not be a problem, as I could simply add movies to a specific Collection, and then tell the rule to avoid removing movies that are in that Collection. But my problem is that Infuse only supports Playlists.
Infuse does pull collections from Plex, but you can't add/remove items to them from Infuse itself.

Would it be possible to have a new condition that checks if a movie is (or isn't) in a Playlist, just like the Collection rule we have at the moment?

<img width="609" alt="image" src="https://github.com/jorenn92/Maintainerr/assets/18260178/d56cb13e-ac63-4987-a885-7e600dd89f59">

Thank you!

**Comment by jorenn92** [comment]
Hey, thanks for giving Maintainerr a shot! 
I added the rules you requested in https://github.com/jorenn92/Maintainerr/pull/615, they'll be available in the next release.

**Comment by alessandro-newzoo** [comment]
@jorenn92 

You are an absolute legend, thank you so much! 
will test it tomorrow when I have a moment. 🖤

**Comment by solid-pixel** [comment]
just realized I posted the last message from my work account 😅 closing!
