### ISSUE TITLE
[Feature Request] Viability of watchlist integration

### ISSUE THREAD

**Issue by jorenn92** [Maintainerr/Maintainerr#626]
Is it viable to add watchlist integration now that shared watchlists is a thing?

**Comment by mrsdoubtfire613** [comment]
I'm interpreting this being able to find if a piece of media is in a/multiple watch lists and then create rules using this information (ie: delete an unwatched movie that's older than 60 days UNLESS it's currently in someone's watchlist and it hasn't been in the watchlist for >90 days).  If we're talking about the same thing then I agree, this integration would be great.

**Comment by jorenn92** [comment]
Yes, i'd like to implement exactly that.. Initially, this was not feasible due to watchlists being associated exclusively with the logged-in user's account. Maintainerr could only retrieve the watchlists of the admin account, as it was authenticated with that specific user.

There is a possibility that the situation has changed now. Plex has expanded the watchlist feature, allowing users to share their watchlists with others, and there may even be an option to make them public. Consequently, it might now be feasible to utilize the watchlists of users who have made them public.

**Comment by misteriks** [comment]
When configuring a rule I was exactly looking for that filter so yes, would be a great addition!

**Comment by clincher61** [comment]
Even if only the admin account watchlist could be queried, I think it's still viable.  

As an admin myself, a user/friend could request something I want to watch before I could request it, so I add it to my watchlist to remember to watch.  It would be great if you could set a set rule as @mrsdoubtfire613 explained except just querying the admin account...: 

> (ie: delete an unwatched movie that's older than 60 days UNLESS it's currently in _the admins_ watchlist and it hasn't been in the watchlist for >90 days)

I'm not too concerned if it's on another users watchlist.... they could request it again if they want to see it.
