### ISSUE TITLE
Run rules based on a specific user

### ISSUE THREAD

**Issue by mada199122** [Maintainerr/Maintainerr#668]
is it possible to run a rules based on a specific user in my plex server?

Thanks

**Comment by jorenn92** [comment]
There are rule values designed to aid in filtering media from specific users. Without knowledge of your specific use case, I can't provide more detailed information than that.

FYI, kindly pose your questions on https://github.com/jorenn92/Maintainerr/discussions or on Discord in the future, to avoid cluttering this issues section.

**Comment by mada199122** [comment]
ok sorry I'll post it there
thanks
