### ISSUE TITLE
[Feature Request] Add Personal User Ratings to Values

### ISSUE THREAD

**Issue by seliku** [Maintainerr/Maintainerr#678]
I am missing more individual user control over the media that is going to be deleted. I was wondering if the Plex User Rating (this 5 Stars  above the play button) can be used to filter movies and shows. It is easy to handle also with a remote control. I think this would be the easiest way for an user to let the admin that this media is good and important for him.

![Screenshot 2023-12-23 141306](https://github.com/jorenn92/Maintainerr/assets/12709254/7d35ddb9-0e57-4af9-ac1e-4275c72388c1)

I can explain my parents that if they give this movie/show only 1 star it will be deleted but if they like to keep it and watch it again then they should give it a high star rating.

BTW i tried the Value "Plex - Rating" but this refers to some other ratings.

**Comment by jorenn92** [comment]
This was released in 1.7.1 with the `Plex - user rating` rule.
