### ISSUE TITLE
[BUG] Plex Rule: "Plex - Last episode added at" order affected by Plex Episode Sorting Oldest First Vs Newest First

### ISSUE THREAD

**Issue by kaishichan** [Maintainerr/Maintainerr#687]
**Describe the bug**
"Plex - Last episode added at" is pulling the last item in a collection returned by the plex api. Here it is assumed that the last item in the collection is the last episode (most recently aired). However if you have "Plex Episode Sorting: Newest First", the last item in the collection will be the oldest episode (first aired episode of season) not the last episode (most recently aired).

https://github.com/jorenn92/Maintainerr/blob/f3a30743b00503612106ff2d17986f42d0adbe82/server/src/modules/rules/getter/plex-getter.service.ts#L349

Suggest the code take into account the highest "index" value of the collection for the last item in the collection.

To Reproduce you'll need the Plex API call to pull children metadata of a season
"/library/metadata/<Season ID>/children?X-Plex-Token=" or getChildrenMetadata()

And in Plex you'll need to edit a library, change the episode sorting between Oldest First vs Newest First
![image](https://github.com/jorenn92/Maintainerr/assets/6711340/0ddb1c69-2fad-4651-8c5f-e9484237b8c5)

Let library sorting to one, and call the api for the episode collection. Change the sorting then call the same api for episode collection. You'll notice the ordering is different and last item in the collection is not the same.

Attaching example collection calls
[API Output with Plex Library Setting Newest First.txt](https://github.com/jorenn92/Maintainerr/files/13783368/API.Output.with.Plex.Library.Setting.Newest.First.txt)
[API Output with Plex Library Setting Oldest First.txt](https://github.com/jorenn92/Maintainerr/files/13783369/API.Output.with.Plex.Library.Setting.Oldest.First.txt)

**Comment by jorenn92** [comment]
Hey, thanks for this report & good find! 

I pushed a fix in #708. It'll be available in the next release.

**Comment by kaishichan** [comment]
awesome, thanks!
