### ISSUE TITLE
https:// disappears on container restart for plex hostname

### ISSUE THREAD

**Issue by mrtargaryen** [Maintainerr/Maintainerr#699]
After entering the Overseerr plex.direct URL with https:// at the start and saving it (connecting successfully to plex) it works great. If I restart the Maintainerr container in docker the preceding https:// disappears and plex is inaccessible. to Maintainerr and I have to readd the https:// save and reconnect. 

Maintainerr>Settings>Plex>Hostname or IP

**Device (please complete the following information):**
 - OS: Windows 11 (WSL2)
 - Docker version 24.0.7, build afdd53b

**Comment by jorenn92** [comment]
Hey!
It's normal for the 'https://' portion to disappear from the field. When 'https://' is added during configuration, it triggers a change in the plex_ssl flag in the database. This flag is then utilized to enforce the connection over https. Simply refreshing the browser should also cause the 'https://' portion to disappear.

The reason it suddenly stops working after a container restart is puzzling. You might want to try opening the maintainerr.sqlite database file with an SQL editor to ensure the plex_ssl flag (in the settings table) remains consistent between container restarts.

**Comment by mrtargaryen** [comment]
> Hey! It's normal for the 'https://' portion to disappear from the field. When 'https://' is added during configuration, it triggers a change in the plex_ssl flag in the database. This flag is then utilized to enforce the connection over https. Simply refreshing the browser should also cause the 'https://' portion to disappear.
> 
> The reason it suddenly stops working after a container restart is puzzling. You might want to try opening the maintainerr.sqlite database file with an SQLite editor to ensure the plex_ssl flag (in the settings table) remains consistent between container restarts.

The problem doesn't appear to be occurring any longer. I don't know why it did that. Everything is running well. Thanks.

**Comment by jorenn92** [comment]
> > Hey! It's normal for the 'https://' portion to disappear from the field. When 'https://' is added during configuration, it triggers a change in the plex_ssl flag in the database. This flag is then utilized to enforce the connection over https. Simply refreshing the browser should also cause the 'https://' portion to disappear.
> > The reason it suddenly stops working after a container restart is puzzling. You might want to try opening the maintainerr.sqlite database file with an SQLite editor to ensure the plex_ssl flag (in the settings table) remains consistent between container restarts.
> 
> The problem doesn't appear to be occurring any longer. I don't know why it did that. Everything is running well. Thanks.

Great, thanks for letting me know!
