### ISSUE TITLE
Unable to get Plex Rating rule to work.

### ISSUE THREAD

**Issue by SteveStonerson** [Maintainerr/Maintainerr#703]
Unable to get the Plex Rating rule to actually work. Currently have **Plex Rating/Smaller/Number/3** and it will not populate any movies. 

Logs show: 
2:51:07 PM     LOG [RuleExecutorService] Executing rules for 'Movies Leaving Soon'
2:51:07 PM     LOG [RuleExecutorService] Execution of rules for 'Movies Leaving Soon' done.

Have tried multiple different combinations of the rule set with no luck, also have had no issues with other rule types. Have doubled checked that I actually have media that is rated less than 3 and there is a solid amount of 2's and lower. 

 - OS: UnRaid IBRACORP Docker
 - Version: jorenn92/maintainerr:latest

**Comment by jorenn92** [comment]
I agree that the rating rule is a bit lacking at the moment. Currently, it fetches the Rotten Tomatoes / IMDb / TMDB / TVDB audience score (depending on what's configured for your library).

The ratings have been extended in Feature Request #705 & Pull Request #709. In the next release, there'll be more control over what kind of rating you'd like to use (user, audience, critic).

One thing to note, though: the ratings are always on a scale from 0 to 10. So, for example, a 76% Rotten Tomatoes score would be represented as '7.6' in Maintainerr's rating rule.

**Comment by jorenn92** [comment]
Closing this now, feel free to create a new issue if you still experience problems with the new rating rules,
