### ISSUE TITLE
[Feature Request] Tag support for Movies in collections to be excluded

### ISSUE THREAD

**Issue by jl94x4** [Maintainerr/Maintainerr#753]
**Is your feature request related to a problem? Please describe.**
You can't currently exclude movies based on a collection tag for a collection they are in such as PMM tags all collections made with PMM [...]

**Describe the solution you'd like**
Allow movies in a collection defined by tag to be excluded from deletion rules

**Describe alternatives you've considered**
As above

**Comment by jorenn92** [comment]
I can't seem to be able to get tags of a collection. Instead, I'm able to access labels. Are you referring to labels?
