### ISSUE TITLE
Won't Connect to Plex

### ISSUE THREAD

**Issue by t34wrj** [Maintainerr/Maintainerr#832]
I also have the same error as #536 (now closed), running v.2.0.0. Plex authenticates but whichever of the three servers I select results in these errors:

[maintainerr] | 04/02/2024 18:17:18  [WARN] [PlexApiService] Plex api communication failure.. Is the application running?
[maintainerr] | 04/02/2024 18:17:18  [DEBUG] [PlexApiService] Cannot read properties of undefined (reading 'machineIdentifier')
[maintainerr] | 04/02/2024 18:17:20  [WARN] [PlexApiService] Plex api communication failure.. Is the application running?
[maintainerr] | 04/02/2024 18:17:20  [DEBUG] [PlexApiService] Cannot read properties of undefined (reading 'MediaContainer')
[maintainerr] | 04/02/2024 18:17:20  [DEBUG] [SettingsService] Cannot read properties of undefined (reading 'version')
[maintainerr] | 04/02/2024 18:19:47  [INFO] [SettingsService] Settings updated
[maintainerr] | 04/02/2024 18:19:47  [WARN] [PlexApiService] Plex api communication failure.. Is the application running?
[maintainerr] | 04/02/2024 18:19:47  [DEBUG] [PlexApiService] Cannot read properties of undefined (reading 'MediaContainer')
[maintainerr] | 04/02/2024 18:19:47  [WARN] [PlexApiService] Plex api communication failure.. Is the application running?
[maintainerr] | 04/02/2024 18:19:47  [DEBUG] [PlexApiService] Cannot read properties of undefined (reading 'machineIdentifier')
[maintainerr] | 04/02/2024 18:19:48  [WARN] [PlexApiService] Plex api communication failure.. Is the application running?
[maintainerr] | 04/02/2024 18:19:48  [DEBUG] [PlexApiService] Cannot read properties of undefined (reading 'MediaContainer')
[maintainerr] | 04/02/2024 18:19:48  [DEBUG] [SettingsService] Cannot read properties of undefined (reading 'version')

This even happens for the server address that works in Overseerr.

_Originally posted by @t34wrj in https://github.com/jorenn92/Maintainerr/issues/536#issuecomment-1925871926_

**Comment by jorenn92** [comment]
Hmm, are you using a secure connection? What’s the value of your Plex servers ‘secure connection’ setting? 

Have you tailed Plex’s debug log when testing the connection? Does it log anything at all?

Also, be aware you have to save the connection first before testing.

**Comment by t34wrj** [comment]
Yes. I have it set to required, which works in Overseer, but I'm assuming might not here for some reason?

Plex does log the attempt - 'Platform 'Maintainerr' not matched by plugin platform requirements '.

Thank for your help.

**Comment by jorenn92** [comment]
I haven’t seen that error yet. 

Does it work when the setting is set to ‘preferred’? It should work with ‘required’ if you select a secure connection, but it’s worth a try..

What Plex version are you using?

**Comment by jorenn92** [comment]
I've identified the problem. The SSL property won't be added correctly. You can work around it for now by adding 'https://' in front of your hostname before saving.

**Comment by t34wrj** [comment]
Thank you - adding https:// fixed this issue for me.
