### ISSUE TITLE
[Bug] DVR related show wont show up on collection page

### ISSUE THREAD

**Issue by corotte** [Maintainerr/Maintainerr#835]
**Describe the bug**
When using rules for a library filled with DVR recorded show from Plex DVR, they seem to be found but crash the collection view page. The page is black. Unable to test or see poster of the show. The collection show the number of episode that matched the rules on the tile where the collection are listed.

NOTE : show are not requested in sonarr

**To Reproduce**
Create whatever rules on a library filled with DVR recorded show from Plex DVR
(i created a rule to automatically delete show aged of 90 days)

**Expected behavior**
Able to access the collection page. Show black poster if nothing found.

**Screenshots**
![black screen](https://github.com/jorenn92/Maintainerr/assets/5565254/b56fdf18-1681-4453-b181-e78b33bc5f1c)
![Tile](https://github.com/jorenn92/Maintainerr/assets/5565254/fc95f26b-cbe7-44dc-b891-520b14b151be)

**Device :**
OS: Linux Mint 21.2 Cinnamon
latest released docker image 2.0.0

EDIT : corrected typo

**Comment by corotte** [comment]
related to #826. Did not see it until i submit. Sorry

**Comment by jorenn92** [comment]
Could you try to replicate the issue with the develop image once https://github.com/jorenn92/Maintainerr/pull/848 is merged? That PR includes a possible solution.

**Comment by corotte** [comment]
Trying right now. 
It now appear.
So far, seem to work.

**Comment by jorenn92** [comment]
> Trying right now. It now appear. So far, seem to work.

Great! Let me know if you notice any other strange behavior. I’ll release a patch release soon.
