### ISSUE TITLE
Action for content not listed in Radarr/Sonarr/Overseer

### ISSUE THREAD

**Issue by corotte** [Maintainerr/Maintainerr#889]
**Is your feature request related to a problem? Please describe.**
I record content from PLEX live TV into a separate library.
Those content are not requested in Overseer and not added in Radarr/Sonarr since they are recording of live TV.
I want to be able to clean those recording before filling up the disk space but the action only seem to take place via Radarr and Sonarr.
The rule work with the exclusion but the action does not.
the episodes stay and even the number of day before deletion go oposite (show 1 when they should show 0 and be deleted, 2 if they where supposed to be deleted 1 days ago, and so on )

**Describe the solution you'd like**
Add a PLEX DELETE action

![maintainerr](https://github.com/jorenn92/Maintainerr/assets/5565254/9b3a6f58-1101-4849-b837-16f6efe9c292)

**Comment by jorenn92** [comment]
Hmm, there’s a fallback mechanism in case deletion through radarr/sonarr is not possible. 🤔

I think this is a bug since it clearly didn’t kick in in your case. Do you happen to have logs?

**Comment by corotte** [comment]
I'm using the docker version 2.0.1 into Linux Mint
I found the log file on the mapped volume. Hope it help.
NOTE : There are 3 rules with the same name but the updated one is the one i tryed to force working to test it out.
[maintainerr-2024-02-10.log](https://github.com/jorenn92/Maintainerr/files/14230008/maintainerr-2024-02-10.log)

**Comment by corotte** [comment]
UPDATE : it seem to be working just fine now

i did a maintenance on my server 3 weeks ago and had to restart the whole machine.
I also manually delete the long list of episodes that where supposed to be deleted.
Sine then, it work as expected.

I even restarted just plex media server for the last update and still working.

look like there was something "hung" that prevent the deletion but unable to catch what it was.
